# Site
repository: nehapspathak/nehapspathak.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1


# Personal info
name: Kumari Neha
title: Data Scientist
email: nehapspathak@gmail.com / nehak@iiitd.ac.in
website: www.github.com/nehapspathak/nehapspathak.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: nehapspathak
github_username:  nehapspathak
stackoverflow_username: "3603139/nehapspathak"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: nehapspathak
linkedin_username: nehapspathak
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Neha and I'm a PhD Research Scholar at IIIT Delhi, India. My interest lies in Computational Social Science and Natural Language Processing.
  I have also worked on Natural Language Understanding and Natural Languuage Inference Task. 
  I am most skilled in: <mark>Python</mark>, <mark>Machine Learning</mark>, <mark>Deep Learning</mark>, <mark>Backend (MongoDb)</mark>, <mark>Magento (CMS)</mark>, <mark>Process Mining</mark> <mark>AWS</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
      
      title: CamPros at CASE 2022 Task 1: Transformer-based Multilingual Protest News Detection
      link: https://github.com/nehapspathak/campros
      additional_links:
          - title: nehapspathak/nehapspathak.github.io
          icon: fab fa-github
          url: 
          quote: > 
            Protest on Twitter
          description: |
            Socio-political protests often lead to grave consequences when they occur. The early detection of such protests is very important for taking early precautionary measures. However, the main shortcoming of protest event detection is the scarcity of sufficient training data for specific language categories, which makes it difficult to train data-hungry deep learning models effectively. Therefore, cross-lingual and zero-shot learning models are needed to detect events in various low-resource languages. This paper proposes a multi-lingual cross-document level event detection approach using pre-trained transformer models developed for Shared Task 1 at CASE 2022. The shared task constituted four subtasks for event detection at different granularity levels, i.e., document level to token level, spread over multiple languages (English, Spanish, Portuguese, Turkish, Urdu, and Mandarin). Our system achieves an average $F_1$ score of $0.73$ for document-level event detection tasks. Our approach secured $2^{nd}$ position for the Hindi language in subtask 1 with an F1 score of $0.80$. While for Spanish, we secure 4th position with an F1 score of 0.69.
      
      title: The Pursuit of Being Heard: An Unsupervised Approach to Narrative Detection in Online Protest.
      link: https://precog.iiit.ac.in/pubs/ASONAM_2022_Unsupervised_Stance.pdf
      additional_links:
          - title: nehapspathak/nehapspathak.github.io
          icon: fab fa-github
          url: 
          quote: > 
            Protest on Twitter
          description: |
              Protests and mass mobilization are scarce; however, they may lead to dramatic outcomes when they occur. Social media such as Twitter has become a center point for the organization and development of online protests worldwide. It becomes crucial to decipher various narratives shared during an online protest to understand people’s perceptions. In this work, we propose an unsupervised clustering-based framework to understand the narratives present in a given online protest. Through a comparative analysis of tweet clusters in 3 protests around government policy bills, we contribute novel insights about narratives shared during an online protest. Across case studies of government policy-induced online protests in India and the United Kingdom, we found familiar mass mobilization narratives across protests. We found reports of on-ground activities and call-to-action for people’s participation narrative clusters in all three protests under study. We also found protest-centric narratives in different protests, such as skepticism around the topic. The results from our analysis can be used to understand and compare people’s perceptions of future mass mobilizations.
      
        title: A Tale of Two Sides: Study of Protesters and Counter-protesters on \#CitizenshipAmendmentAct Campaign on Twitter
        link: https://dl.acm.org/doi/abs/10.1145/3501247.3531584
        # link_text: Project Website
        additional_links:
          - title:  nehapspathak/nehapspathak.github.io
            icon: fab fa-github
            url: https://precog.iiit.ac.in/resources.html
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          #CitizenshipAmendmentAct on Twitter
        description: | # this will include new lines to allow paragraphs
          Online social media platforms have evolved into a significant place for debate around socio-political phenomena such as government policies and bills. Studying online debates on such topics can help infer people’s perception and acceptance of the happenings. At the same time, various inauthentic users that often pollute the democratic discussion of the subject need to be weeded out from the debate. The characterization of a campaign keeping in mind various forms of involved actors thus becomes very important. On December 12, 2019, Citizenship Amendment Act (CAA) was enacted by the Indian Government, triggering a debate on whether the act was unfair. In this work, we investigate the user’s perception of the #CitizenshipAmendmentAct on Twitter, as the campaign unrolled with divergent discourse in the country. Keeping the campaign participants as the prime focus, we study 9,947,814 tweets produced by 275,111 users during the starting 3 months of protest. Our study includes the analysis of user engagement, content, and network properties with online accounts divided into authentic (genuine users) and inauthentic (bots, suspended, and deleted) users. Our findings show different themes in shared tweets among protesters and counter-protesters. We find presence of inauthentic users on both side of discourse, with counter-protesters having more inauthentic users than protesters. The follow network of the users suggests homophily among users on the same side of discourse and connection between various inauthentic and authentic users. This work contributes to filling the gap of understanding the role of users (from both sides) in a less studied geo-location, India.
      
      title: Zero-shot Entity and Tweet Characterization with Designed Conditional Prompts and Contexts
      link: https://arxiv.org/abs/2204.08405
      additional_links:
          - title: nehapspathak/nehapspathak.github.io
          icon: fab fa-github
          url: 
          quote: > 
            Evaluation of zero-shot language model capabilities of Generative Pretrained Transformer 2
          description: |
            Online news and social media have been the de facto mediums to disseminate information globally from the beginning of the last decade. However, bias in content and purpose of intentions are not regulated, and managing bias is the responsibility of content consumers. In this regard, understanding the stances and biases of news sources towards specific entities becomes important. To address this problem, we use pretrained language models, which have been shown to bring about good results with no task-specific training or few-shot training. In this work, we approach the problem of characterizing Named Entities and Tweets as an open-ended text classification and open-ended fact probing problem.We evaluate the zero-shot language model capabilities of Generative Pretrained Transformer 2 (GPT-2) to characterize Entities and Tweets subjectively with human psychology-inspired and logical conditional prefixes and contexts. First, we fine-tune the GPT-2 model on a sufficiently large news corpus and evaluate subjective characterization of popular entities in the corpus by priming with prefixes. Second, we fine-tune GPT-2 with a Tweets corpus from a few popular hashtags and evaluate characterizing tweets by priming the language model with prefixes, questions, and contextual synopsis prompts. Entity characterization results were positive across measures and human evaluation.

    
      title: Truth and travesty intertwined: a case study of \#SSR counterpublic campaign
      link: https://dl.acm.org/doi/abs/10.1145/3487351.3492717
      additional_links:
          - title: nehapspathak/nehapspathak.github.io
          icon: fab fa-github
          url: 
          quote: > 
            #ShushantSinghRajput on Twitter
          description: |
            Twitter has emerged as a prominent social media platform for activism and counterpublic narratives. The counterpublics leverage hashtags to build a diverse support network and share content on a global platform that counters the dominant narrative. This paper applies the framework of connective action on the counter-narrative campaign over the cause of death of# SushantSinghRajput. We combine descriptive network, modularity, and hashtag based topical analysis to identify three major mechanisms underlying the campaign: generative role taking, hashtag-based narratives and formation of alignment network towards a common cause. Using the case study of# SushantSinghRajput, we highlight how connective action framework can be used to identify different strategies adopted by counterpublics for the emergence of connective action.
          
      title: Is change the only constant? Profile change perspective on# LokSabhaElections2019
      link: https://arxiv.org/abs/1909.10012
      additional_links:
          - title: nehapspathak/nehapspathak.github.io
          icon: fab fa-github
          url: 
          quote: > 
            #MainBhiChowkidar on Twitter
          description: |
            Users on Twitter are identified with the help of their profile attributes that consists of username, display name, profile image, to name a few. The profile attributes that users adopt can reflect their interests, belief, or thematic inclinations. Literature has proposed the implications and significance of profile attribute change for a random population of users. However, the use of profile attribute for endorsements and to start a movement have been under-explored. In this work, we consider #LokSabhaElections2019 as a movement and perform a large-scale study of the profile of users who actively made changes to profile attributes centered around #LokSabhaElections2019. We collect the profile metadata for 49.4M users for a period of 2 months from April 5, 2019 to June 5, 2019 amid #LokSabhaElections2019. We investigate how the profile changes vary for the influential leaders and their followers over the social movement. We further differentiate the organic and inorganic ways to show the political inclination from the prism of profile changes. We report how the addition of election campaign related keywords lead to spread of behavior contagion and further investigate it with respect to "Chowkidar Movement" in detail.
          
          
#           title: Truth and travesty intertwined: a case study of \#SSR counterpublic campaign
#       link: https://dl.acm.org/doi/abs/10.1145/3487351.3492717
#       additional_links:
#           - title: nehapspathak/nehapspathak.github.io
#           icon: fab fa-github
#           url: 
#           quote: > 
#             #ShushantSinghRajput on Twitter
#           description: |
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
      
        title: Zeon Solutions Pvt. Ltd. (now Perficient)
        link: https://www.perficient.com/
        # link_text: boringcompany.com
        sub_title: Junior Software Engineer
        caption: July 2012 - July 2014
        quote: >
          Building eCommerce wesbites
        description: | # this will include new lines to allow paragraphs
            Build Model-View-Controller (MVC) based eCommerce Website. We used Magento framework for building eCommerce website. I was involved in developement and maintainace of the various clients that needed eCommnece website to support their business. I have developed B2B and B2C eCommerce websites.

        title: DRDO, Delhi
        link: https://www.drdo.gov.in/
        sub_title: Junior Research Fellow
        caption: Jan 2018 - Dec 2019
        quote: >
          Building applications based on Social Media Analytics
#         description: |

        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IIIT Delhi
        caption: 2018 - present
        sub_title: Ph.D. Research Scholar
        quote: >
          Ph.D. in Computational Social Science
#         description: | # this will include new lines to allow paragraphs

        title: IIIT Bhubaneshwar
        caption: 2015 - 2017
        sub_title: Masters of Technology (Computer Science)
        
        
        title: Nagpur University
        caption: 2008 - 2012
        sub_title: Bachelor of Engineering
          

#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
